### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by swasun** [determinated/Aion-4.7.5-Rework-GiGatR00n-Source-Developing-Project#1]
Client crashes when the player is in battle or rest mode and try to identify an object/set manastone/enchant item.

I tried to check to player state in CM_MANASTONE to prevent that, but this packet should be received after the client clicked on the button that triggered the crash.

**Comment by determinated** [comment]
Well i've tried to fix this but i wasnt able. Is something about actions, stance. Instead of crashing a message should show up like "You are not able to do this on combat mode" or something like that.

**Comment by swasun** [comment]
It is, but I am not sure if there is an interaction with the server before the crash, so we can prevent this behavior, or if it is only a client side bug, which I hope not.

**Comment by determinated** [comment]
I dont remember where in ragezone Gigatroon said that this was a client side bug.

**Comment by swasun** [comment]
I tried another client and it's worked.

**Comment by determinated** [comment]
So the problem is the client??? You just changed the client?

**Comment by determinated** [comment]
Can you share what client you've used?

**Comment by swasun** [comment]
Yes just that. This one: https://www.aions-revenge.de/downloads
I just changed the language pack, but in either languages it's working correctly. And btw about the HTML rendering issue, it's working with their german language pack but not my english one, so I guess it's an HTML tag issue afterall.

**Comment by determinated** [comment]
I cant believe the client crash was just a client side thing. I spend many hours trying to find a missing/error code on source.

**Comment by swasun** [comment]
Haha I feel you I did spend hours on that as well.

**Comment by determinated** [comment]
Yeah xD
