### ISSUE TITLE
Kinah looting

### ISSUE THREAD

**Issue by swasun** [determinated/Aion-4.7.5-Rework-GiGatR00n-Source-Developing-Project#10]
Sometimes the kinahs in a loot are appearing twice like that:
![kinah_looting](https://user-images.githubusercontent.com/25248913/64986680-d713c780-d8c7-11e9-9cb5-fa59b52bbaa8.PNG)

Is it a normal behavior of this release?

**Comment by determinated** [comment]
Probably because have 2 drops for kinah in npc_drop.xml
