### ISSUE TITLE
I need to join the team.

### ISSUE THREAD

**Issue by jielcc2** [determinated/Aion-4.7.5-Rework-GiGatR00n-Source-Developing-Project#13]
Please add my account：jielcc2

**Comment by determinated** [comment]
Pass me your discord profile.

It's just me and Swasun

**Comment by jielcc2** [comment]
OK, good luck to you.

**Comment by determinated** [comment]
No you understand me wrong xD I've said that for now who is working is just me and Swasun. You can join XD do you have discord?

**Comment by jielcc2** [comment]
yea

**Comment by determinated** [comment]
Send me

**Comment by jielcc2** [comment]
Name: jielcc2
Account number: 13350437571@163.com

**Comment by jielcc2** [comment]
Looking forward to joining your project! !

**Comment by determinated** [comment]
Let's maintain our contact with Skype. Is better even to transfer files ok.

**Comment by jielcc2** [comment]
I will download discord at night, please wait





At 2019-09-22 00:04:20, "Alison Carvalho" <notifications@github.com> wrote:


Let's maintain our contact with Skype. Is better even to transfer files ok.
