### ISSUE TITLE
HTML rendering of tutorial

### ISSUE THREAD

**Issue by swasun** [determinated/Aion-4.7.5-Rework-GiGatR00n-Source-Developing-Project#3]
In all the tutorials (for example keyboard movement), the HTML text is not rendered and is print instead. I didn't notice any HTML errors though.

**Comment by determinated** [comment]
Maybe this is a client thing

**Comment by swasun** [comment]
Can you please share where you downloaded your client, to verify if it's mine? Mine is from rWorld private server.

**Comment by determinated** [comment]
Mine is a old client that a friend that used to play with me have shared with me.

**Comment by swasun** [comment]
Have you encountered this issue with your client?

**Comment by swasun** [comment]
I tried another language pack and it worked.
