### ISSUE TITLE
Quest "A ribbit out of water"

### ISSUE THREAD

**Issue by swasun** [determinated/Aion-4.7.5-Rework-GiGatR00n-Source-Developing-Project#49]
Starting step 3, you can't finish the quest cause the steps are repeating.

**Comment by determinated** [comment]
The quest is working! You have to take the rabbit that's following you to the lake. You'll have a quest update and boom. Done!

![image](https://user-images.githubusercontent.com/17693617/65835044-ff33fb00-e2b7-11e9-9029-c21ac3592a8e.png)
