### ISSUE TITLE
A specific aggressive mob that doesn't attack

### ISSUE THREAD

**Issue by swasun** [determinated/Aion-4.7.5-Rework-GiGatR00n-Source-Developing-Project#53]
It's only this mob:
![image](https://user-images.githubusercontent.com/25248913/65831868-37d6d300-e2be-11e9-8ea1-2e540a8c6976.png)

**Comment by determinated** [comment]
Weird because they all are attacking me without problems.

![image](https://user-images.githubusercontent.com/17693617/65834882-e9bdd180-e2b5-11e9-8c9e-ef1f582d957f.png)
