### ISSUE TITLE
Training dummy at Akarios

### ISSUE THREAD

**Issue by swasun** [determinated/Aion-4.7.5-Rework-GiGatR00n-Source-Developing-Project#55]
At Akarios in Poeta, a destroyed training dummy takes more time to repop than in retail.

**Comment by determinated** [comment]
The HP is right according with http://aiondatabase.net/us/npc/700100/

![image](https://user-images.githubusercontent.com/17693617/65834257-abbdaf00-e2af-11e9-8b58-0f15e55c96ab.png)

![image](https://user-images.githubusercontent.com/17693617/65834262-b11af980-e2af-11e9-991f-8197b012110e.png)

**Comment by determinated** [comment]
The time was 5 minutes and now is set to 30 seconds!
