### ISSUE TITLE
Some mobs are superimposed

### ISSUE THREAD

**Issue by swasun** [determinated/Aion-4.7.5-Rework-GiGatR00n-Source-Developing-Project#56]
[Poeta, Kabarah Strip Mine]
![image](https://user-images.githubusercontent.com/25248913/65831939-f692f300-e2be-11e9-8846-b0faa4f68fe4.png)
![image](https://user-images.githubusercontent.com/25248913/65831941-fdba0100-e2be-11e9-915c-28a5bafad190.png)

[Verteron]
![image](https://user-images.githubusercontent.com/25248913/65831934-e7ac4080-e2be-11e9-8e57-0bb53be17c57.png)

**Comment by determinated** [comment]
Cool easy to fix! Just mobs with double spawns
