### ISSUE TITLE
Useless quest symbol

### ISSUE THREAD

**Issue by swasun** [determinated/Aion-4.7.5-Rework-GiGatR00n-Source-Developing-Project#62]
In Verteron (exact location in the screen below) there is quest item symbol but there is nothing to gather:
![image](https://user-images.githubusercontent.com/25248913/65832051-2b537a00-e2c0-11e9-9380-5068cdd476bf.png)

**Comment by determinated** [comment]
WTF

**Comment by determinated** [comment]
I've tested this. I went to the location and i dont have this problem. Maybe is quest related. Maybe should have something spawned in the location.

**Comment by determinated** [comment]
Was just a underground spawn. Now it's fixed!
![image](https://user-images.githubusercontent.com/17693617/65834115-11a93700-e2ae-11e9-9241-d435f27d3eb6.png)
