### ISSUE TITLE
Reset of Tursin Gateblocker

### ISSUE THREAD

**Issue by swasun** [determinated/Aion-4.7.5-Rework-GiGatR00n-Source-Developing-Project#66]
At the Dukaki Settlement of Verteron, Tursin Gateblocker is reseting if you get away from a few meters. Don't remember if it's the regular behavior?
![image](https://user-images.githubusercontent.com/25248913/65832213-14f9ee00-e2c1-11e9-8327-bedfbbfe2bb2.png)

**Comment by determinated** [comment]
This is a normal behavior.
