### ISSUE TITLE
Delete post offer

### ISSUE THREAD

**Issue by swasun** [determinated/Aion-4.7.5-Rework-GiGatR00n-Source-Developing-Project#8]
The find group is working, but the Delete Post button is not available (stay in gray, even with two players in the group).

**Comment by determinated** [comment]
auto_group.java i think there is the problem

**Comment by swasun** [comment]
The autogroup feature seems related to instance autogrouping. My issue is related to the LFG find group feature.

**Comment by determinated** [comment]
Maybe a missing packet.

**Comment by swasun** [comment]
Update: the bug is fixed for a single player group research, and appears again for >= 2 players.
